### ISSUE TITLE
Problem with Saraff.TwainX.NET package on Mac Catalyst 7.0

### ISSUE THREAD

**Issue by Zile1999** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#109]
**Description**

I am trying to develop a MAUI application that should work on multiple platforms (**Windows/MacOS**) using .NET 7.0. I have encountered an issue when using the Saraff.TwainX.NET package for document scanning. The package works fine on Windows, but when the same process is applied to Mac Catalyst 7.0, package does not function.

The error occurring during the project build in VS Code is shown in the attacked image.
![Screenshot 2023-11-14 at 13 22 51](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET/assets/127318733/33eb5b19-61dc-4a67-b9db-bea0125519b0)

Additionally, on the provided link [https://www.nuget.org/packages/Saraff.TwainX.NET#supportedframeworks-body-tab](url) there is a Framework tab listing all compatible version, but Mac Catalyst 7.0 is not marked.

Is it possible to use this package on Mac Catalyst 7.0 at all? If not, are there any potential solutions or alternatives? 

**Versions in use:**
      -MacOS: 13.0
     -.NET MAUI 7.0 (Mac Catalyst 7.0)
     - Xcode: 14.3

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @Zile1999 
In first, [Saraff.Twain.NET 1.0.32.732](https://www.nuget.org/packages/Saraff.Twain#supportedframeworks-body-tab) already includes Saraff.TwainX.NET (netstandard2.0)

In your case, the problem is not in the package, but in the installed software for working with TWAIN (.../SDKs/MacOSX.13.1.sdk/System/Library/Frameworks/TWAIN.framework/TWAIN.tbd for architecture x86_64) and apparently this does not correspond to your target platform
