### ISSUE TITLE
Clarify licencing

### ISSUE THREAD

**Issue by strzibny** [saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.NET#16]
Hello,

we are evaluating Saraff for one of our apps and the licensing is confusing. There is both ` COPYING.txt` and `COPYING.LESSER.txt` license files -- one indicating GPL v3, the second LGPL v3 as in some of the files.

It is because the Saraff code is LGPL but depends (uses) GPL code so both licenses has to be taken into account? Or is it up to the user to pick one? Thank you

**Comment by saraff-9EB1047A4BEB4cef8506B29BA325BD5A** [comment]
Hello, @strzibny 
It is because the Saraff.Twain.NET code is LGPL, but depends (GNU Lesser General Public License incorporates the terms and conditions of version 3 of the GNU General Public License) GPL license.
Also, you can see topic about [How to use GNU licenses for your own software](http://www.gnu.org/licenses/gpl-howto.en.html).
